import type { Platform } from "../../shared/viewing-context";
import type { Quiz } from "../../shared/quiz";
import { getUiCopy } from "./copy";
const ROOT_ID = "plottwist-extension-root";
export function mountOverlay(platform: Platform, locale: string, requestQuiz: () => Promise<{ quiz?: Quiz; error?: string }>): void {
  if (document.getElementById(ROOT_ID)) return;
  const copy = getUiCopy(locale); const host = document.createElement("div"); host.id = ROOT_ID;
  const shadow = host.attachShadow({ mode: "open" }); const netflix = platform === "netflix";
  shadow.innerHTML = `<style>:host{all:initial}.backdrop{position:fixed;inset:0;z-index:2147483000;display:grid;place-items:center;padding:24px;background:${netflix ? "rgb(0 0 0/.78)" : "rgb(0 5 13/.76)"};font-family:${netflix ? '"Netflix Sans",sans-serif' : '"Amazon Ember",Arial,sans-serif'};color:#fff}.panel{width:min(460px,100%);padding:${netflix ? "28px" : "24px"};border-radius:${netflix ? "4px" : "8px"};background:${netflix ? "#181818" : "#161e2d"};box-shadow:0 16px 40px rgb(0 0 0/.48)}.eyebrow{margin:0 0 12px;color:${netflix ? "#e50914" : "#00a8e1"};font:700 12px inherit;letter-spacing:.08em}h2{margin:0 0 10px;font-size:24px}.content{margin:0;color:#d2d2d2;font:16px/1.5 inherit;white-space:pre-line}.status{margin-top:18px;color:#b3b3b3}.choices{display:grid;gap:10px;margin-top:20px}.choice{min-height:48px;padding:12px 14px;border:1px solid ${netflix ? "#555" : "#4a5a70"};border-radius:${netflix ? "2px" : "4px"};background:transparent;color:inherit;text-align:left;font:600 16px inherit;cursor:pointer}.choice:hover,.choice:focus-visible{border-color:${netflix ? "#fff" : "#00a8e1"};background:${netflix ? "#333" : "#233047"};outline:0}</style><section class="backdrop" role="dialog" aria-modal="true"><div class="panel"><p class="eyebrow">${copy.eyebrow}</p><h2>${copy.title}</h2><p class="content">${copy.loading}</p><p class="status">${copy.loading}</p><div class="choices"></div></div></section>`;
  document.body.append(host); const content = shadow.querySelector<HTMLElement>(".content")!; const status = shadow.querySelector<HTMLElement>(".status")!; const choices = shadow.querySelector<HTMLElement>(".choices")!;
  void requestQuiz().then((result) => { if (!result.quiz) { content.textContent = result.error ?? "Unable to prepare a quiz."; status.textContent = ""; return; } const quiz = result.quiz; content.textContent = `${quiz.hint}\n\n${quiz.question}`; status.textContent = ""; quiz.choices.forEach((choice, index) => { const option = document.createElement("button"); option.className = "choice"; option.textContent = choice; option.onclick = () => { content.textContent = `${index === quiz.correctChoiceIndex ? "Correct." : "Not quite."} ${quiz.reveal}`; choices.replaceChildren(); window.setTimeout(() => host.remove(), 1800); }; choices.append(option); }); });
}
